In [1]:
import pandas as pd
import re

In [3]:
# Loading Reddit data to a Data Frame
reddit_df = pd.read_csv("../stock_data/reddit_wsb.csv")
reddit_df.head()

,title,score,id,url,comms_num,created,body,timestamp
0,"It's not about the money, it's about sending a...",55,l6ulcx,https://v.redd.it/6j75regs72e61,6,1.611863e+09,NaN,2021-01-28 21:37:41
1,Math Professor Scott Steiner says the numbers ...,110,l6uibd,https://v.redd.it/ah50lyny62e61,23,1.611862e+09,NaN,2021-01-28 21:32:10
2,Exit the system,0,l6uhhn,https://www.reddit.com/r/wallstreetbets/commen...,47,1.611862e+09,The CEO of NASDAQ pushed to halt trading “to g...,2021-01-28 21:30:35
3,NEW SEC FILING FOR GME! CAN SOMEONE LESS RETAR...,29,l6ugk6,https://sec.report/Document/0001193125-21-019848/,74,1.611862e+09,NaN,2021-01-28 21:28:57
4,"Not to distract from GME, just thought our AMC...",71,l6ufgy,https://i.redd.it/4h2sukb662e61.jpg,156,1.611862e+09,NaN,2021-01-28 21:26:56

In [4]:
# Drop unused columns
reddit_df = reddit_df.drop(columns=["url", "created"])

In [5]:
# Convert timestamp to datetime format
reddit_df['timestamp'] = pd.to_datetime(reddit_df['timestamp'])
reddit_df.head()

,title,score,id,comms_num,body,timestamp
0,"It's not about the money, it's about sending a...",55,l6ulcx,6,NaN,2021-01-28 21:37:41
1,Math Professor Scott Steiner says the numbers ...,110,l6uibd,23,NaN,2021-01-28 21:32:10
2,Exit the system,0,l6uhhn,47,The CEO of NASDAQ pushed to halt trading “to g...,2021-01-28 21:30:35
3,NEW SEC FILING FOR GME! CAN SOMEONE LESS RETAR...,29,l6ugk6,74,NaN,2021-01-28 21:28:57
4,"Not to distract from GME, just thought our AMC...",71,l6ufgy,156,NaN,2021-01-28 21:26:56

In [16]:
# Remove special charater from Title and Body columms
def clean_text(text):

    # Remove all the special characters
    text = ' '.join(re.findall(r'\w+', text))
    
    return text

reddit_df["title"] = reddit_df["title"].fillna('').apply(str)
reddit_df["title"] = reddit_df["title"].apply(lambda x : clean_text(x))

In [17]:
# Remove special charater from Body columm and fill NaN
reddit_df["body"] = reddit_df["body"].fillna('').apply(str)
reddit_df["body"] = reddit_df["body"].apply(lambda x : clean_text(x))
reddit_df.head()

,title,score,id,comms_num,body,timestamp
0,It s not about the money it s about sending a ...,55,l6ulcx,6,,2021-01-28 21:37:41
1,Math Professor Scott Steiner says the numbers ...,110,l6uibd,23,,2021-01-28 21:32:10
2,Exit the system,0,l6uhhn,47,The CEO of NASDAQ pushed to halt trading to gi...,2021-01-28 21:30:35
3,NEW SEC FILING FOR GME CAN SOMEONE LESS RETARD...,29,l6ugk6,74,,2021-01-28 21:28:57
4,Not to distract from GME just thought our AMC ...,71,l6ufgy,156,,2021-01-28 21:26:56

In [18]:
# Export to CSV
reddit_df.to_csv('Reddit_Cleaned.csv',index=False)